#!/usr/bin/env python3
"""Generate the per-version Minecraft build (minecraft/) for one release.

    port.py 26.3                     # write ./minecraft for 26.3
    port.py 1.20.1 --out /tmp/b      # somewhere else
    port.py --list                   # show family/loader plan for every release

Inputs: versions/versions.json (official metadata), client/platform/families.json
(which adapter sources + build generation serve which versions). Output is a
self-contained Gradle build that compiles the in-tree client core and the
family's platform sources for every loader that both exists upstream and is
implemented by the family. Nothing is copied: sources are referenced from the
repository, so an mc/<version> branch is just main + this generated directory.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import stat
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
HERE = os.path.dirname(os.path.abspath(__file__))


def vkey(v: str):
    return tuple(int(p) for p in re.findall(r"\d+", v))


def load(p):
    with open(os.path.join(ROOT, p), encoding="utf-8") as fh:
        return json.load(fh)


def family_for(mc: str, families):
    for f in families["families"]:
        if vkey(f["minecraft"]["min"]) <= vkey(mc) <= vkey(f["minecraft"]["max"]):
            return f
    return None


def plan(mc: str):
    """Return (entry, family, [(loader_label, loader_cfg, upstream_info)], reasons)."""
    matrix = load("versions/versions.json")
    families = load("client/platform/families.json")
    entry = next((e for e in matrix["versions"] if e["minecraft"] == mc), None)
    if entry is None:
        raise SystemExit(f"{mc} is not a stable release in versions/versions.json")
    fam = family_for(mc, families)
    targets, reasons = [], {}
    for loader in ("fabric", "forge"):
        up = entry["loaders"][loader]
        label = "legacyfabric" if loader == "fabric" and up.get("flavor") == "legacyfabric" else loader
        if not up.get("available"):
            reasons[label] = up.get("reason", "unavailable upstream")
            continue
        if fam is None or label not in fam["loaders"]:
            reasons[label] = "not implemented yet for this Minecraft version (no adapter family)"
            continue
        targets.append((label, fam["loaders"][label], up))
    return entry, fam, targets, reasons


def render(path, tokens):
    with open(path, encoding="utf-8") as fh:
        s = fh.read()
    for k, v in tokens.items():
        s = s.replace("@" + k + "@", str(v))
    left = re.findall(r"@[A-Z_]+@", s)
    if left:
        raise SystemExit(f"unreplaced tokens in {path}: {sorted(set(left))}")
    return s


def write(path, text, mode=None):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
    if mode:
        os.chmod(path, mode)


def generate(mc: str, out: str):
    entry, fam, targets, reasons = plan(mc)
    if not targets:
        raise SystemExit(f"nothing buildable for {mc}: {reasons}")
    buildgens = {t[1]["buildgen"] for t in targets}
    if len(buildgens) != 1:
        raise SystemExit(f"{mc}: loaders use different build generations {buildgens}; split builds not supported yet")
    buildgen = buildgens.pop()
    tdir = os.path.join(HERE, "templates", buildgen)
    gradle_version = max((t[1]["gradle"] for t in targets), key=vkey)
    if os.path.isdir(out):
        shutil.rmtree(out)
    os.makedirs(out)
    java = entry["java"]
    props = {
        "minecraft_version": mc,
        "mod_version": load_version(),
        "maven_group": "io.github.ravoxx.mcvoice",
        "java_version": java,
        "org.gradle.jvmargs": "-Xmx3g",
        "org.gradle.caching": "true",
    }
    includes = []
    for label, cfg, up in targets:
        variants = [src for v in fam.get("variants", [])
                    if vkey(v["minecraft"]["min"]) <= vkey(mc) <= vkey(v["minecraft"]["max"]) for src in v["sources"]]
        tokens = {"MC": mc, "JAVA": java, "FAMILY": fam["id"], "PLUGIN_VERSION": cfg["plugin_version"],
                  "VARIANT_DIRS": ", ".join("'" + v + "'" for v in variants)}
        write(os.path.join(out, label, "build.gradle"), render(os.path.join(tdir, f"{label}.gradle"), tokens))
        includes.append(f"include '{label}'")
        if label in ("fabric", "legacyfabric"):
            props["fabric_loader"] = up["loader"]
            api = up.get("fabric_api") or up.get("legacy_fabric_api")
            if api:
                props["fabric_api"] = api
        if label == "forge":
            props["forge_version"] = up["version"]
    write(os.path.join(out, "settings.gradle"),
          render(os.path.join(tdir, "settings.gradle"), {"MC": mc, "INCLUDES": "\n".join(includes)}))
    write(os.path.join(out, "gradle.properties"),
          "# GENERATED by tools/port-version/port.py - do not edit by hand.\n"
          + "".join(f"{k}={v}\n" for k, v in props.items()))
    write(os.path.join(out, "gradle", "wrapper", "gradle-wrapper.properties"),
          "distributionBase=GRADLE_USER_HOME\ndistributionPath=wrapper/dists\n"
          f"distributionUrl=https\\://services.gradle.org/distributions/gradle-{gradle_version}-bin.zip\n"
          "networkTimeout=10000\nvalidateDistributionUrl=true\nzipStoreBase=GRADLE_USER_HOME\nzipStorePath=wrapper/dists\n")
    shutil.copy(os.path.join(HERE, "wrapper", "gradle-wrapper.jar"), os.path.join(out, "gradle", "wrapper", "gradle-wrapper.jar"))
    for f in ("gradlew", "gradlew.bat"):
        shutil.copy(os.path.join(HERE, "wrapper", f), os.path.join(out, f))
    os.chmod(os.path.join(out, "gradlew"), os.stat(os.path.join(out, "gradlew")).st_mode | stat.S_IEXEC)
    meta = {
        "minecraft": mc,
        "family": fam["id"],
        "buildgen": buildgen,
        "gradle": gradle_version,
        "java": java,
        "build_jdk": entry["build_jdk"],
        "loaders": [t[0] for t in targets],
        "not_built": reasons,
    }
    write(os.path.join(out, "build-info.json"), json.dumps(meta, indent=2) + "\n")
    write(os.path.join(out, "README.md"),
          f"# MCVoice for Minecraft {mc}\n\nGenerated by `tools/port-version/port.py {mc}` from `main`.\n"
          f"Family `{fam['id']}`, build generation `{buildgen}`, Gradle {gradle_version}, Java {java}.\n\n"
          f"Loaders built here: {', '.join(meta['loaders'])}.\n\n"
          + "".join(f"* {k}: not built - {v}\n" for k, v in reasons.items())
          + "\nBuild: `cd minecraft && ./gradlew build`; jars land in `minecraft/<loader>/build/libs/`.\n")
    print(json.dumps(meta))
    return meta


def load_version():
    with open(os.path.join(ROOT, "client", "gradle.properties"), encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("mod_version="):
                return line.split("=", 1)[1].strip()
    raise SystemExit("mod_version missing")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("minecraft", nargs="?")
    ap.add_argument("--out", default=os.path.join(ROOT, "minecraft"))
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--json", action="store_true", help="with --list: machine readable")
    args = ap.parse_args()
    if args.list:
        matrix = load("versions/versions.json")
        rows = []
        for e in matrix["versions"]:
            _, fam, targets, reasons = plan(e["minecraft"])
            rows.append({"minecraft": e["minecraft"], "family": fam["id"] if fam else None,
                         "loaders": [t[0] for t in targets], "build_jdk": e["build_jdk"], "reasons": reasons})
        if args.json:
            print(json.dumps(rows))
        else:
            for r in rows:
                print(f"{r['minecraft']:>8}  {str(r['family']):8}  {','.join(r['loaders']) or '-':22}  {r['reasons']}")
        return 0
    if not args.minecraft:
        ap.error("minecraft version required")
    generate(args.minecraft, os.path.abspath(args.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
